### ISSUE TITLE
ES6 import Support

### ISSUE THREAD

**Issue by zhea55** [hajnalben/ClickableRequires#1]
Can you make this plugin work with es6 import?

**Comment by hajnalben** [comment]
I will try. However I'm not sure if it can be achieved easily. Different module bundlers may use different logic for the import. 
Maybe I can improve it to work with webpack.

**Comment by zhea55** [comment]
Thanks, happy to hear that.

**Comment by hajnalben** [comment]
ES6 import is now supported. Please report any bugs you find.
