### ISSUE TITLE
Keybinding for immediate show of tooltip

### ISSUE THREAD

**Issue by mjlescano** [hajnalben/ClickableRequires#2]
Hi! Is there a way to set a key to show the tooltip immediately on hover? Is really cumbersome to have to wait to see the tooltip if I want to navigate thru a series of files.

I almost know nothing of python + sublime, but, if you point me where to start I could send a PR :)

**Comment by hajnalben** [comment]
Hi!
I believe this wait time is a restriction in Sublime. The default hover action for definitions works the same way. 
A solution could be a new plugin command which can be mapped to any key and opens the related npm page on click. Is that fit your needs?
Sorry for the delayed answer, I missed the notification of this issue. :/

**Comment by hajnalben** [comment]
By the way the API reference can be found at: https://www.sublimetext.com/docs/3/api_reference.html
