### ISSUE TITLE
Issue with es6 import using multiple lines.

### ISSUE THREAD

**Issue by Darkle** [hajnalben/ClickableRequires#4]
Hi, I think I've stumbled on to a bug with es6 imports. With the following code:
```js
import {
  getInitialSettingsFromMainProcess as getInitialState,
  identity,
  handleRendererWindowError
} from '../../common/renderers/utils.js'
import appActions from './actions/actionsIndex.js'
import views from './views/viewsIndex.js'
```
 `utils.js` is not underlined and the popup on hover only shows up for `actionsIndex.js` and `viewsIndex.js`, but not `utils.js`.

It's' not a huge deal, but I thought I should mention it.

Thanks for the package, it's handy.

**Comment by hajnalben** [comment]
Hey!
I have fixed this in release 0.0.7. :)
