### ISSUE TITLE
Import in Typescript does not work

### ISSUE THREAD

**Issue by redice44** [hajnalben/ClickableRequires#6]
```javascript
import foo from './foo'; // Doesn't have a pop up
const f = require('./foo'); // Does have a pop up. Expected behavior
```

**Comment by hajnalben** [comment]
Can you please provide more details? I cannot reproduce this.
![image](https://user-images.githubusercontent.com/7289336/40163727-dfce356c-59b7-11e8-98ab-68b3c306b0d9.png)

**Comment by redice44** [comment]
After a little bit more testing, it seems that the link only appears if I hover over a "./" or "../" part of the reference. As soon as I hover over the name it goes away. 

I'm on OSX 10.13.4 and ST 3.1.1. Doesn't seem to be anything in the console in ST either.

**Comment by septagram** [comment]
Would be really cool if it was fixed. Some of our modules aren't imported with `./` nor `../`, e.g.:

```
import SomeSharedModule from 'shared/foo/bar`;
```

@hajnalben Would you suppose it's ClickableRequires' problem or a conflict with the TypeScript plugin? In case it's the latter, is there any way I can override priority for displaying those popups?

**Comment by hajnalben** [comment]
https://github.com/hajnalben/ClickableRequires/blob/master/README.md#webpack-or-other-module-handlers must solve it. ;)
